apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sil-ingress
spec:
  virtualhost:
    fqdn: sil-api
  routes:
    - conditions:
      - prefix: /
      services:
        - name: sil-api
          port: 80