apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sp-ingress
spec:
  virtualhost:
    fqdn: sp-api
  routes:
    - conditions:
      - prefix: /
      services:
        - name: sp-api
          port: 80